name: Deploy QA

on:
  push:
    branches:
      - qa

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: qa

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Deploy en EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          command_timeout: 10m
          script: |
            set -e
            cd /home/ec2-user/app

            # Actualizar código
            git pull origin qa

            # Inyectar URL real del servidor en el frontend
            sed -i "s|%API_URL%|http://${{ secrets.EC2_HOST }}:8080|g" frontend/public/index.html

            # .env raíz para docker-compose (variables de postgres y healthcheck)
            cat > .env << ENVEOF
            DB_NAME=voucherdb
            DB_USER=admin
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            ENVEOF

            # .env del servicio Node.js
            cat > servicios/servicio-usuarios/.env << ENVEOF
            DB_HOST=postgres
            DB_PORT=5432
            DB_NAME=voucherdb
            DB_USER=admin
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            ADMIN_EMAIL=admin@certjoin.com
            ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}
            PARTNER_EMAIL=partner@certjoin.com
            PARTNER_PASSWORD=${{ secrets.PARTNER_PASSWORD }}
            STRIPE_PUBLISHABLE_KEY=${{ secrets.STRIPE_PUBLISHABLE_KEY }}
            STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}
            STRIPE_WEBHOOK_SECRET=${{ secrets.STRIPE_WEBHOOK_SECRET }}
            FRONTEND_URL=http://${{ secrets.EC2_HOST }}:3000
            PORT=8081
            NODE_ENV=production
            REFRESH_TOKEN_TTL_DAYS=7
            SESSION_TIMEOUT_MINUTES=30
            MAX_LOGIN_ATTEMPTS=10
            RATE_LIMIT_WINDOW_MINUTES=15
            RATE_LIMIT_MAX_REQUESTS=100
            MOODLE_URL=http://moodle-mock:8082
            MOODLE_TOKEN=b7e1f736de1ed7eb52b09ac6a8f18c60
            MOODLE_ROLE_ID=5
            MOODLE_MOCK=false
            ENVEOF

            # Crear directorio de logs
            mkdir -p logs/usuarios

            # Actualizar buildx
            BUILDX_VER=$(curl -s https://api.github.com/repos/docker/buildx/releases/latest | grep '"tag_name"' | cut -d'"' -f4)
            sudo mkdir -p /usr/local/lib/docker/cli-plugins
            sudo curl -SL "https://github.com/docker/buildx/releases/download/${BUILDX_VER}/buildx-${BUILDX_VER}.linux-amd64" \
              -o /usr/local/lib/docker/cli-plugins/docker-buildx
            sudo chmod +x /usr/local/lib/docker/cli-plugins/docker-buildx

            # Levantar contenedores
            docker compose down --remove-orphans
            docker compose up -d --build

            # Verificar estado
            docker compose ps
